#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

# Update package list and install HAProxy
sudo apt-get -y update
apt-get -y install haproxy

# Edit HAProxy configuration file
server_config=\
"
frontend http_front
        bind *:80
        mode http
        default_backend http_back
backend http_back
        balance roundrobin
        server 6928-web-01 :80 check
        server 6928-web-02 18.208.153.152:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# Enable HAProxy to be started by init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Restart HAProxy
sudo service haproxy restart
